# 数据库服务器配置
[db-scrm]
driver        = "mysql"
host          = "mysql.beta.**.cn"
port          = 33306
username      = "weixin-**-user"
password      = "***"
database      = "weixin-**"
charset       = "utf8mb4"
max_conn      = 50
max_idle_conn = 10
ping          = true
